apiVersion: v1
kind: Namespace
metadata:
  name: saufautomat
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: card-review-state-pvc
  namespace: saufautomat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: card-review-service
  namespace: saufautomat
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: NodePort
  selector:
    app: card-review
  ports:
    - name: http
      protocol: TCP
      port: 60004
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-review
  namespace: saufautomat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-review
  template:
    metadata:
      labels:
        app: card-review
        dockertag: {{TAG}}
    spec:
      containers:
        - name: card-review
          image: openalcoholics/card-review:{{TAG}}
          imagePullPolicy: Always
          env:
            - name: CARDS_FILE
              value: "/data/cards.json"
            - name: REVIEWS_FILE
              value: "/data/reviews.json"
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: "/data"
              name: card-review-state-volume
      volumes:
        - name: card-review-state-volume
          persistentVolumeClaim:
            claimName: card-review-state-pvc
