name: Build/Publish docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to dockerhub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u torbencarstens --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA})
      - name: Build the tagged Docker image
        run: docker build -t openalcoholics/card-review:${{steps.vars.outputs.tag}} .
      - name: Push the tagged Docker image
        run: docker push torbencarstens/openalcoholics/card-review:${{steps.vars.outputs.tag}}
      - name: update TAG
        run: sed -i -e "s/{{TAG}}/${{steps.vars.outputs.tag}}/g" .kubernetes/manifest.yaml
      - uses: danielr1996/kubectl-action@1.0.0
        name: apply config
        with:
          kubeconfig: ${{ secrets.K8SCONF }}
          args: delete -n saufautomat rs -l "'app in (card-review), dockertag notin (${{steps.vars.outputs.tag}})'"
      - uses: danielr1996/kubectl-action@1.0.0
        name: apply config
        with:
          kubeconfig: ${{ secrets.K8SCONF }}
          args: apply -f .kubernetes/manifest.yaml

